### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by pmbauer** [draios/sysdig#378] opened 2015-06-17 00:07 UTC
I can consistently induce a kernel panic when running sysdig, forcing an `REISUB`
This usually happens within a few seconds of running sysdig.
It happens when running from inside X or directly from ttyX.

```
sysdig:    version 0.1.101
System:    Host: saffron Kernel: 3.19.0-21-generic x86_64 (64 bit) Desktop: Unity 7.3.2
           Distro: Ubuntu 15.04 vivid
Machine:   System: LENOVO product: 20BXCTO1WW v: ThinkPad T450s
           Mobo: LENOVO model: 20BXCTO1WW v: SDK0E50512 STD Bios: LENOVO v: JBET46WW (1.11 ) date: 03/02/2015
CPU:       Dual core Intel Core i7-5600U (-HT-MCP-) speed/max: 858/3200 MHz
Graphics:  Card: Intel Broadwell-U Integrated Graphics
           Display Server: X.Org 1.17.1 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.0hz, 2560x1600@60.0hz
           GLX Renderer: Mesa DRI Intel HD Graphics 5500 (Broadwell GT2) GLX Version: 3.0 Mesa 10.5.2
Network:   Card-1: Intel Ethernet Connection (3) I218-LM driver: e1000e
           Card-2: Intel Wireless 7265 driver: iwlwifi
Drives:    HDD Total Size: 512.1GB (17.6% used) ID-1: model: SAMSUNG_MZ7LN512
Info:      Processes: 269 Uptime: 7 min Memory: 4511.8/11895.2MB Client: Shell (bash) inxi: 2.2.16
```

(picture of panic)
https://www.dropbox.com/s/2tc0fgzyz9pvbib/2015-06-16%2016.49.11.jpg?dl=0

**Comment by gianlucaborello** [comment] 2015-06-17 00:25
Bad indeed.

Decoding the address of the kernel panic, it seems to come from here:

```
(gdb) info line *(ppm_ioctl)+0x3da
Line 764 of "/root/sysdig/driver/main.c" starts at address 0x1b77 <ppm_ioctl+967> and ends at 0x1b96 <ppm_ioctl+998>.
```

Which is:

```
#ifdef for_each_process_thread
		for_each_process_thread(p, t) {
#else
		for_each_process(p) {
```

And it's highly likely, since it's part of some new code introduced with 0.1.101.

We'll do our best to replicate this and ask for help if we're unable to reproduce.

**Comment by ldegio** [comment] 2015-07-17 16:59
@pmbauer, I believe the fix that solves https://github.com/draios/sysdig/issues/391 should solve this one as well. Could you try if the problem disappears when compiling from the dev branch?

**Comment by pmbauer** [comment] 2015-07-17 17:01
@ldegio Wonderful. Swamped with work today but will try to get some bandwidth for this later this weekend. Thank you!

**Comment by ldegio** [comment] 2015-07-24 23:53
@pmbauer did you get a chance to test? Can we close this issue?

**Comment by pmbauer** [comment] 2015-07-25 01:33
No. I'm moving. I spent 20 minutes here and don't have the time to finish building on a clean vm and test this; I'm sorry I indicated otherwise last Friday. If there is a more-recent build of sysdig available with the bug fix I can test it, but don't have time to build it all from scratch.

**Comment by gianlucaborello** [comment] 2015-07-31 01:07
We believe this was fixed on 0.1.102 that was just released today. Could you please try and report your feedback?

**Comment by lilydjwg** [comment] 2015-07-31 14:45
I got this error in the past too. After updating to 0.1.102, I don't see it any more (to be exact, it doesn't happen on first few runs).

**Comment by gianlucaborello** [comment] 2015-07-31 15:51
That's good news, I'm going to close this for the moment then.

**Closed by gianlucaborello** 2015-07-31 15:51 UTC
