### ISSUE TITLE
sysdig installation failed at latest version of CoreOS

### ISSUE THREAD

**Issue by linfan** [draios/sysdig#419] opened 2015-08-21 10:28 UTC
It seems the latest version of CoreOS changed the kernel header files folder, it's no `/lib/modules/4.1.5-coreos/build` or `/lib/modules/4.1.5-coreos/source` at all.

Below is the error message:

```
$ docker run -i -t --name sysdig --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro sysdig/sysdig
* Setting up /usr/src links from host
ls: cannot access /host/usr/src: No such file or directory
* Unloading sysdig-probe, if present
rmmod: ERROR: Module sysdig_probe is not currently loaded
* Running dkms autoinstall
Error! echo
Your kernel headers for kernel 4.1.5-coreos cannot be found at
/lib/modules/4.1.5-coreos/build or /lib/modules/4.1.5-coreos/source.
* Trying to load a system sysdig-probe, if present
* Trying to load a dkms sysdig-probe, if present
* Trying to find precompiled sysdig-probe for 4.1.5-coreos
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.1.102-x86_64-4.1.5-coreos-79c237830473a423ff789458f3acfac3.ko
Download failed, consider compiling your own sysdig-probe and loading it or getting in touch with the sysdig community
root@fcdc81c6573e:/#
```

Below information about /lib/modules/4.1.5-coreos/ folder may be useful for trace the problem.

```
# ls /lib/modules/4.1.5-coreos/
build   modules.alias      modules.builtin      modules.dep      modules.devname  modules.softdep  modules.symbols.bin
kernel  modules.alias.bin  modules.builtin.bin  modules.dep.bin  modules.order    modules.symbols  source

# ls /lib/modules/4.1.5-coreos/source
/lib/modules/4.1.5-coreos/source  <-- it's a broken link file

# ls /lib/modules/4.1.5-coreos/build/

# ls /lib/modules/4.1.5-coreos/kernel/
arch  crypto  drivers  fs  lib  mm  net  security
```

**Comment by linfan** [comment] 2015-08-21 12:08
I think the problem is caused by CoreOS removed header files from `/lib/modules/4.1.5-coreos/build/` folder in the latest image.

One possible solution may be let sysdig docker image to mount `/lib/modules/4.1.5-coreos/build/` folder with a separated volumn, and download linux header into it before run `sysdig-probe-loader`. It seems kernel headers won't come back otherwise.

**Comment by gianlucaborello** [comment] 2015-08-21 18:29
Fixed with 562b0ae. In general, it takes us about 24 hour to support a new alpha, we still don't have good automation going on around that. stable and beta should always be covered by the time they get promoted.

**Closed by gianlucaborello** 2015-08-21 18:29 UTC

**Comment by tdeheurles** [comment] 2015-11-20 15:36
hi, 
It seems that the problem is still there with CoreOS 845.

```
./sysdig.sh
* Setting up /usr/src links from host
ls: cannot access /host/usr/src: No such file or directory
* Unloading sysdig-probe, if present
rmmod: ERROR: Module sysdig_probe is not currently loaded
* Running dkms autoinstall
Error! echo
Your kernel headers for kernel 4.2.2-coreos-r1 cannot be found at
/lib/modules/4.2.2-coreos-r1/build or /lib/modules/4.2.2-coreos-r1/source.
* Trying to load a system sysdig-probe, if present
* Trying to load a dkms sysdig-probe, if present
* Trying to find precompiled sysdig-probe for 4.2.2-coreos-r1
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.5.1-x86_64-4.2.2-coreos-r1-47d77585832c3ca7e6061f678bddbd43.ko
Download succeeded, loading module
```

Same here, no headers in the build folder.

```
➜  ~  ls /lib/modules/4.2.2-coreos-r1/build
➜  ~
```

**Comment by gianlucaborello** [comment] 2015-11-20 17:27
Look at the last line, "Download succeeded, loading module", it's saying that it's working, the error message above are completely benign and they happen because sysdig-probe-loader "desperately" tries to compile sysdig-probe before giving up and downloading a precompiled one, which indeed works.

**Comment by tdeheurles** [comment] 2015-11-20 18:28
thanks.

But it's not supposed to launch the UI ?

Will read some doc ^^

**Comment by gianlucaborello** [comment] 2015-11-20 18:29
Once you are in the container, you can run "sysdig" or "csysdig" depending on what you need to launch. We don't launch anything by default because we can't predict what parameters/filters/chisels the user might need.

**Comment by tdeheurles** [comment] 2015-11-20 18:33
And it's working fine.
Sorry for such a question.

Thank you for support.
