### ISSUE TITLE
FLAGS and original argument value

### ISSUE THREAD

**Issue by HugoGuiroux** [draios/sysdig#486] opened 2015-11-25 19:43 UTC
Currently, a flag syscall argument is converted from linux constant (e.g., `O_APPEND` for `open(2)`) to `PPM` constants at kernel-level inside `ppm_filler`.
The results is that we lose the initial argument value if this value contains other bits than the ones we consider for conversion (e.g., `open("/dev/null", 42)` gives `flags=3(O_RDWR)`).

Ideally, `sysdig` should prints the initial `flags` value with the flags identified (`flags=42(O_RDWR)`).

**Comment by ldegio** [comment] 2015-11-30 17:42
The problem is that, depending on the syscall, the original constants are not guaranteed across systems. They can change based on the OS version and architecture. Note also that we support decoding the trace files on Mac and Windows, where the original constant values might not exist at all.

For these reasons, sysdig converts these flags into a system independent format. The correct way to include a missing flag is adding its PPM equivalent. This is typically pretty easy to do by extending the filler.

I'm closing this issue, feel free to reopen if there's something I miss.

**Closed by ldegio** 2015-11-30 17:42 UTC

**Comment by HugoGuiroux** [comment] 2015-11-30 19:17
I understand the concern about system dependent flags why you need to convert the flags to there PPM equivalent at kernel level.

One possibility is to store both the PPM values as well as the original values inside the trace, so we can print how the flags were interpreted on the monitored machine, as well as the real value given to the syscall. But this will double the size to store a flag inside the trace, and it may not be acceptable.
