### ISSUE TITLE
ZSH completion problems

### ISSUE THREAD

**Issue by masterkorp** [draios/sysdig#292] opened 2015-01-19 13:14 UTC
After upgrading to sysdig ``0.1.93`` zsh completions fails

```
_sysdig:209: bad pattern: starting]              \\n    (-F --fatfile){-F,--fatfile}[Enable
_sysdig:209: bad pattern: starting]              \\n    (-F --fatfile){-F,--fatfile}[Enable
_sysdig:209: bad pattern: starting]              \\n    (-F --fatfile){-F,--fatfile}[Enable
```
Using Zsh version ``zsh 5.0.7 (x86_64-unknown-linux-gnu)``

**Comment by vampolo** [comment] 2015-01-19 14:53
Hi @masterkorp,

How did you install `sysdig` ? The problem you are referring should be caused by #290 that should be fixed in the `dev` branch.

Just compiled `dev` branch and it works for me. Proof:

```
➜  ~  sysdig -
--chisel           -c   -- Run a given chisel                                                                                           
--chisel-info      -i   -- Get a detailed chisel description                                                                            
--compress         -z   -- Enables compression for stored tracefiles                                                                    
--debug            -D   -- Capture events about sysdig itself                                                                           
--displayflt       -d   -- Make the given filter a display one                                                                          
--exclude-users    -E   -- Don't create the user/group tables when starting                                                             
--fatfile          -F   -- Enable fatfile mode                                                                                          
--help             -h   -- Print this help                                                                                              
--json             -j   -- Emit output as JSON                                                                                          
--list             -l   -- List the fields that can be used for filtering                                                               
--list-chisels     -cl  -- lists the available chisels                                                                                  
--list-events      -L   -- List the events that the engine supports                                                                     
-lv                     -- Verbosely list the fields that can be used for filtering                                                     
--numevents        -n   -- Stop capturing after <num> events                                                                            
--print            -p   -- Specify the event format                                                                                     
--print-ascii      -A   -- Only print the text portion of data buffers                                                                  
--print-base64     -b   -- Print data buffers in base64                                                                                 
--print-hex        -x   -- Print data buffers in hex                                                                                    
--print-hex-ascii  -X   -- Print data buffers in hex and ASCII                                                                          
--progress         -P   -- Print progress on stderr while processing trace files                                                        
--quiet            -q   -- Do not print events on the screen                                                                            
--read             -r   -- Read events from <readfile.scap>                                                                             
--snaplen          -s   -- Capture the first <len> bytes of each I/O buffer                                                             
--summary          -S   -- Print the event summary when the capture ends                                                                
--timetype         -t   -- Change the way event time is displayed                                                                       
--verbose          -v   -- Verbose output                                                                                               
--write            -w   -- Write events to <writefile.scap>                                                                             
```

**Comment by masterkorp** [comment] 2015-01-19 15:03
[How the package is built](https://aur.archlinux.org/packages/sy/sysdig/PKGBUILD)

**Comment by vampolo** [comment] 2015-01-19 15:08
looks to me that `aur` build scripts gets the stable version.
Unfortunately the stable version does not have the fix we are talking about yet.

Your best bet is to compile from git yourself the `dev` branch, or wait for next release. Isn't compiling the `dev` branch feasible in your case ?

**Comment by masterkorp** [comment] 2015-01-20 10:36
@vampolo Thanks I will use the sysdig-git package for now and edit to fetch from the dev branch.

**Closed** 2015-01-20 10:36 UTC
