### ISSUE TITLE
fd.directory filter does not behave as documented

### ISSUE THREAD

**Issue by charles-dyfis-net** [draios/sysdig#306] opened 2015-02-03 00:26 UTC
The description for `fd.directory` specifies its behavior as follows:

> If the fd is a file, the directory that contains it.

However, its actual behavior does match this. Filtering on `fd.directory=/tmp`, for instance, returns `opendir()` and `readdir()` calls against `/tmp`, but does not include operations on `/tmp/hello`.

Observed against sysdig 0.1.94.

**Comment by ldegio** [comment] 2015-02-09 18:39
fd.directory has been designed to only match the FDs inside the specific directory, not in its subdirectories. That's because for subdirectories you can use something like

fd.name contains /tmp

I'm closing the issue, feel free to reopen if you think this doesn't address what you need.

**Comment by charles-dyfis-net** [comment] 2015-02-09 18:44
In the above-given example, `/tmp/hello` was expected to be a file, not a directory. Thus, I'm seeing behavior inconsistent with the design goal described above.

**Comment by ldegio** [comment] 2015-02-09 18:51
In that case it's a bug. Reopening.

**Comment by Hefeweizen** [comment] 2015-02-11 19:33
Confirmed still present in 0.1.96  (both in ubuntu and mac os x client)

I don't mind making the .scap.z file available; just can't attach it here.

$ sysdig -zr bug306.20150211.1125.scap.z fd.directory contains tmp
3490 11:07:58.709658498 0 ls (5406) < openat fd=3(<d>/tmp) 
3531 11:07:58.709759271 0 ls (5406) > close fd=3(<d>/tmp) 
3532 11:07:58.709759712 0 ls (5406) < close res=0 
5918 11:08:03.058218977 0 bash (5408) < openat fd=3(<d>/tmp) 
5927 11:08:03.058260812 0 bash (5408) > close fd=3(<d>/tmp) 
5928 11:08:03.058261193 0 bash (5408) < close res=0 
6020 11:08:03.058805326 0 bash (5409) < openat fd=3(<d>/tmp) 
6029 11:08:03.058832752 0 bash (5409) > close fd=3(<d>/tmp) 
6030 11:08:03.058833098 0 bash (5409) < close res=0 
6069 11:08:03.059100821 0 bash (3836) < open fd=3(<f>/tmp/sh-thd-1062265610) name=/tmp/sh-thd-1062265610 flags=294(O_TRUNC|O_EXCL|O_CREAT|O_WRONLY) mode=0 
6070 11:08:03.059109422 0 bash (3836) > write fd=3(<f>/tmp/sh-thd-1062265610) size=8 
6071 11:08:03.059121630 0 bash (3836) < write res=8 data=/tmp/... 
6072 11:08:03.059122174 0 bash (3836) > write fd=3(<f>/tmp/sh-thd-1062265610) size=1 
6073 11:08:03.059123478 0 bash (3836) < write res=1 data=. 
6075 11:08:03.059125518 0 bash (3836) < open fd=4(<f>/tmp/sh-thd-1062265610) name=/tmp/sh-thd-1062265610 flags=1(O_RDONLY) mode=0 
6076 11:08:03.059126046 0 bash (3836) > close fd=3(<f>/tmp/sh-thd-1062265610) 
6077 11:08:03.059126364 0 bash (3836) < close res=0 
6088 11:08:03.059137926 0 bash (3836) > dup fd=4(<f>/tmp/sh-thd-1062265610) 
6089 11:08:03.059138159 0 bash (3836) < dup res=0(<f>/tmp/sh-thd-1062265610) 
6090 11:08:03.059138753 0 bash (3836) > close fd=4(<f>/tmp/sh-thd-1062265610) 
6091 11:08:03.059138859 0 bash (3836) < close res=0 
6092 11:08:03.059153045 0 bash (3836) > ioctl fd=0(<f>/tmp/sh-thd-1062265610) request=5401 argument=7FFF77201E70 
6093 11:08:03.059153629 0 bash (3836) < ioctl res=-25(ENOTTY) 
6094 11:08:03.059155156 0 bash (3836) > lseek fd=0(<f>/tmp/sh-thd-1062265610) offset=0 whence=1(SEEK_CUR) 
6095 11:08:03.059155541 0 bash (3836) < lseek res=0 
6096 11:08:03.059156356 0 bash (3836) > read fd=0(<f>/tmp/sh-thd-1062265610) size=128 
6097 11:08:03.059157770 0 bash (3836) < read res=9 data=/tmp/b... 
6098 11:08:03.059176002 0 bash (3836) > ioctl fd=0(<f>/tmp/sh-thd-1062265610) request=5401 argument=7FFF77201E70 
6099 11:08:03.059176270 0 bash (3836) < ioctl res=-25(ENOTTY) 
6100 11:08:03.059176513 0 bash (3836) > lseek fd=0(<f>/tmp/sh-thd-1062265610) offset=0 whence=1(SEEK_CUR) 
6101 11:08:03.059176649 0 bash (3836) < lseek res=9 
6102 11:08:03.059176943 0 bash (3836) > read fd=0(<f>/tmp/sh-thd-1062265610) size=128 
6103 11:08:03.059177303 0 bash (3836) < read res=0 data= 
9281 11:08:10.971164539 0 touch (5411) < open fd=3(<f>/tmp/foo) name=/tmp/foo flags=70(O_NONBLOCK|O_CREAT|O_WRONLY) mode=0 
9282 11:08:10.971166058 0 touch (5411) > dup fd=3(<f>/tmp/foo) 
9283 11:08:10.971166962 0 touch (5411) < dup res=0(<f>/tmp/foo) 
9284 11:08:10.971169156 0 touch (5411) > close fd=3(<f>/tmp/foo) 
9285 11:08:10.971169360 0 touch (5411) < close res=0 
9288 11:08:10.971182767 0 touch (5411) > close fd=0(<f>/tmp/foo) 
9289 11:08:10.971183043 0 touch (5411) < close res=0 
10895 11:08:13.979910055 0 touch (5412) < open fd=3(<f>/tmp/baz) name=/tmp/baz flags=70(O_NONBLOCK|O_CREAT|O_WRONLY) mode=0 
10896 11:08:13.979912422 0 touch (5412) > dup fd=3(<f>/tmp/baz) 
10897 11:08:13.979913502 0 touch (5412) < dup res=0(<f>/tmp/baz) 
10898 11:08:13.979915021 0 touch (5412) > close fd=3(<f>/tmp/baz) 
10899 11:08:13.979915471 0 touch (5412) < close res=0 
10902 11:08:13.979925831 0 touch (5412) > close fd=0(<f>/tmp/baz) 
10903 11:08:13.979926053 0 touch (5412) < close res=0 
12748 11:08:17.854824669 0 touch (5413) < open fd=3(<f>/tmp/qux) name=/tmp/qux flags=70(O_NONBLOCK|O_CREAT|O_WRONLY) mode=0 
12749 11:08:17.854826229 0 touch (5413) > dup fd=3(<f>/tmp/qux) 
12750 11:08:17.854827210 0 touch (5413) < dup res=0(<f>/tmp/qux) 
12751 11:08:17.854829207 0 touch (5413) > close fd=3(<f>/tmp/qux) 
12752 11:08:17.854829415 0 touch (5413) < close res=0 
12755 11:08:17.854842286 0 touch (5413) > close fd=0(<f>/tmp/qux) 
12756 11:08:17.854842609 0 touch (5413) < close res=0 
14369 11:08:20.416403770 0 cat (5414) < open fd=3(<f>/tmp/foo) name=/tmp/foo flags=1(O_RDONLY) mode=0 
14370 11:08:20.416404436 0 cat (5414) > fstat fd=3(<f>/tmp/foo) 
14371 11:08:20.416404827 0 cat (5414) < fstat res=0 
14374 11:08:20.416415024 0 cat (5414) > read fd=3(<f>/tmp/foo) size=65536 
14375 11:08:20.416430689 0 cat (5414) < read res=0 data= 
14376 11:08:20.416432897 0 cat (5414) > close fd=3(<f>/tmp/foo) 
14377 11:08:20.416433286 0 cat (5414) < close res=0 
16086 11:08:24.153264341 0 bash (3836) < openat fd=3(<d>/tmp) 
16095 11:08:24.153344311 0 bash (3836) > close fd=3(<d>/tmp) 
16096 11:08:24.153346066 0 bash (3836) < close res=0 
$ sysdig -zr bug306.20150211.1125.scap.z fd.directory=/tmp
3490 11:07:58.709658498 0 ls (5406) < openat fd=3(<d>/tmp) 
3531 11:07:58.709759271 0 ls (5406) > close fd=3(<d>/tmp) 
3532 11:07:58.709759712 0 ls (5406) < close res=0 
5918 11:08:03.058218977 0 bash (5408) < openat fd=3(<d>/tmp) 
5927 11:08:03.058260812 0 bash (5408) > close fd=3(<d>/tmp) 
5928 11:08:03.058261193 0 bash (5408) < close res=0 
6020 11:08:03.058805326 0 bash (5409) < openat fd=3(<d>/tmp) 
6029 11:08:03.058832752 0 bash (5409) > close fd=3(<d>/tmp) 
6030 11:08:03.058833098 0 bash (5409) < close res=0 
16086 11:08:24.153264341 0 bash (3836) < openat fd=3(<d>/tmp) 
16095 11:08:24.153344311 0 bash (3836) > close fd=3(<d>/tmp) 
$ sysdig -zr bug306.20150211.1125.scap.z -c spy_users
3805 11:07:58 vagrant) ls --color=auto -l /tmp
3805 11:08:03 vagrant) rm /tmp/bar
3805 11:08:10 vagrant) touch /tmp/foo
3805 11:08:13 vagrant) touch /tmp/baz
3805 11:08:17 vagrant) touch /tmp/qux
3805 11:08:20 vagrant) cat /tmp/foo
3805 11:08:24 vagrant) rm /tmp/baz /tmp/foo /tmp/qux

**Comment by charles-dyfis-net** [comment] 2015-02-13 16:39
Interesting; I hadn't observed that `fd.directory contains /tmp` would hit on access to files directly within `/tmp`, whereas `fd.directory=/tmp` would not. This makes it sound like `fd.directory` is acting equivalent to `fd.name`, if and only if `fd` is a handle on a directory.

**Comment by Hefeweizen** [comment] 2015-02-13 18:30
In providing the output I wasn't specifically testing fd.directory against fd.name.  I was inattentive in my testing and just tested fd.directory because I edited the previous command line.  However, it appears for this purpose, they're interchangeable.  I get no appreciable results when I use them:

$ sysdig -zr bug306.20150211.1125.scap.z fd.directory contains /tmp > fd.directory
$ sysdig -zr bug306.20150211.1125.scap.z fd.name contains /tmp > fd.name
$ diff fd.directory fd.name 
$

**Comment by Hefeweizen** [comment] 2015-02-13 18:36
Found it!

fd.directory=/tmp/ finds the files.

$ sysdig -zr bug306.20150211.1125.scap.z fd.directory contains /tmp -p "%fd.directory %fd.name" | uniq
/tmp /tmp
/tmp/ /tmp/sh-thd-1062265610
/tmp/ /tmp/foo
/tmp/ /tmp/baz
/tmp/ /tmp/qux
/tmp/ /tmp/foo
/tmp /tmp
$ sysdig -zr bug306.20150211.1125.scap.z fd.directory=/tmp/ -p "%fd.directory %fd.name" | uniq
/tmp/ /tmp/sh-thd-1062265610
/tmp/ /tmp/foo
/tmp/ /tmp/baz
/tmp/ /tmp/qux
/tmp/ /tmp/foo
$ sysdig -zr bug306.20150211.1125.scap.z fd.directory=/tmp -p "%fd.directory %fd.name" | uniq
/tmp /tmp

I would still call this a bug.  I would not expect to have to specify a trailing slash in directory names.

To fix, I see one of two options:
- change the comparison code to consider the directory name with or without the slash
- normalize the internal fd.directory field to either have or not have the trailing slash

While I'm curious what the final implementation will be, I'm not familiar with the codebase enough to suggest one over the other.

**Comment by Hefeweizen** [comment] 2015-02-13 22:49
Created pull request #314 as a suggested solution.

Considering the extrapolated nature of the comparison code I thought the directory name normalization a cleaner approach.  I'm concerned that changing the path name might have unforeseen consequences.

**Comment by ldegio** [comment] 2015-02-15 18:59
I tested the patch and it behaves as expected.

I'm slightly worried about unforeseen consequences as well, but I searched in the chisel directory and it looks like this field is not used by any chisel, so I think we should be ok.

**Comment by ldegio** [comment] 2015-02-15 18:59
and we'll update the baseline on travis.

**Closed by ldegio** 2015-02-15 18:59 UTC
