### ISSUE TITLE
BPF_PROBE variable naming issue

### ISSUE THREAD

**Issue by deepskyblue86** [draios/sysdig#1934] opened 2022-11-10 19:16 UTC
I was about to use sysdig with the container image (on amazon linux) and I noticed that `/usr/bin/scap-driver-loader` and `sysdig`/`csysdig` use two different naming:

- scap-driver-loader has FALCO_BPF_PROBE
- the tools has SYSDIG_BPF_PROBE

Workaround: pass `-e FALCO_BPF_PROBE="" -e SYSDIG_BPF_PROBE=""` to docker

**Comment by FedeDP** [comment] 2022-11-14 10:39
The issue is now fixed; a 0.30.2 is being released! Thanks for the feedback!

**Closed as completed** 2022-11-17 09:38 UTC
