### ISSUE TITLE
sysdig does not compile against glibc 2.31

### ISSUE THREAD

**Issue by ysz** [draios/sysdig#1632] opened 2020-05-13 09:56 UTC
sysdig does not compile against glibc 2.31 

Bundled grpc version 1.8.1 https://github.com/draios/sysdig/blob/dev/CMakeLists.txt#L554 misses this patch https://github.com/grpc/grpc/pull/18950

This looks similar to https://github.com/falcosecurity/falco/issues/921

```bash
src/core/lib/support/log_linux.cc:42:13: error: ambiguating new declaration of ‘long int gettid()’
   42 | static long gettid(void) { return syscall(__NR_gettid); }
      |             ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from src/core/lib/support/log_linux.cc:40:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old declaration ‘__pid_t gettid()’
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
src/core/lib/support/log_linux.cc:42:13: warning: ‘long int gettid()’ defined but not used [-Wunused-function]
   42 | static long gettid(void) { return syscall(__NR_gettid); }
      |             ^~~~~~
make[3]: *** [Makefile:2587: /vagrant/sysdig/build/grpc-prefix/src/grpc/objs/opt/src/core/lib/support/log_linux.o] Error 1
make[2]: *** [CMakeFiles/grpc.dir/build.make:118: grpc-prefix/src/grpc-stamp/grpc-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:668: CMakeFiles/grpc.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by nathan-b** [comment] 2020-06-24 17:48
This looks like a duplicate of #1625

**Closed by nathan-b** 2020-06-24 17:48 UTC
