### ISSUE TITLE
Any way to log the failed http request?

### ISSUE THREAD

**Issue by kxjhwbb** [draios/sysdig#1455] opened 2019-07-17 09:27 UTC
I want to trace some http log with out response
i try  sysdig -c httplog
and sysdig -s2000 -A -c echo_fds blablabla
but only can log the http with response

how to log the http request? thank you~

**Comment by therealbobo** [comment] 2023-04-04 18:21
Hi @kxjhwbb! Here the problem is that `curl` (or any other client that makes an http request) doesn't write on a socket until a connection is established... I think there is no obvious way to circumvent the problem other that a "man in the middle": for example you could use `socat` to forward the traffic to the remote host
```bash
socat TCP-LISTEN:80,fork TCP:<remote-ip>:80
```
In this way your client will establish a connection and `sysdig` will be able to log the request (using the `echo_fds` chisel)!
I'll close this issue but feel free to reopen! 😄

**Closed by therealbobo** 2023-04-04 18:21 UTC
Labels: pinned, feature-request
