### ISSUE TITLE
kernel panic using sysdig on CoreOS alpha (928.0.0)

### ISSUE THREAD

**Issue by meonkeys** [draios/sysdig#522] opened 2016-01-22 18:04 UTC
Please see https://github.com/coreos/bugs/issues/1089 . CoreOS folks asked me to file a bug here.

```
[   68.868083] BUG: unable to handle kernel NULL pointer dereference at 0000000000000589
[   68.869056] IP: [<ffffffffc042fb22>] f_sched_switch_e+0x52/0x140 [sysdigcloud_probe]
[   68.869056] PGD 2d2f5067 PUD eb868067 PMD 0 
[   68.869056] Oops: 0000 [#1] SMP 
[   68.869056] Modules linked in: sysdigcloud_probe(OE) xt_nat xt_mark xt_comment veth xt_conntrack ipt_MASQUERADE nf_nat_masquerade_ipv4 tun iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter nf_nat nf_conntrack br_netfilter bridge stp llc overlay nls_ascii nls_cp437 vfat fat xenfs xen_privcmd ext4 crc16 mbcache jbd2 crc32c_intel hmac drbg aesni_intel mousedev aes_x86_64 xen_blkfront glue_helper lrw gf128mul ablk_helper i2c_piix4 cryptd evdev psmouse ixgbevf i2c_core ata_piix libata scsi_mod acpi_cpufreq tpm_tis tpm button sch_fq_codel ip_tables autofs4
[   68.869056] CPU: 0 PID: 891 Comm: kubelet Tainted: G           OE   4.4.0-coreos #2
[   68.869056] Hardware name: Xen HVM domU, BIOS 4.2.amazon 12/07/2015
[   68.869056] task: ffff88002cddd640 ti: ffff88002d0e4000 task.ti: ffff88002d0e4000
[   68.869056] RIP: 0010:[<ffffffffc042fb22>]  [<ffffffffc042fb22>] f_sched_switch_e+0x52/0x140 [sysdigcloud_probe]
[   68.869056] RSP: 0018:ffff88002d0e7a20  EFLAGS: 00010046
[   68.869056] RAX: 0000000000000001 RBX: ffff88002d0e7a78 RCX: 0000000000000000
[   68.869056] RDX: 0000000000000000 RSI: 000000000000037b RDI: ffff88002d0e7a78
[   68.869056] RBP: ffff88002d0e7a38 R08: 0000000000000000 R09: 0000000000000558
[   68.869056] R10: 00000000007f96b0 R11: ffffc90001d46afd R12: ffffc90001b7a000
[   68.869056] R13: 0000000000000098 R14: ffffc90001bb0000 R15: ffff88002d0e7b30
[   68.869056] FS:  00007f863e7fc700(0000) GS:ffff8803cfc00000(0000) knlGS:0000000000000000
[   68.869056] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   68.869056] CR2: 0000000000000589 CR3: 00000003b912b000 CR4: 00000000001406f0
[   68.869056] Stack:
[   68.869056]  ffffe8ffffc029b8 ffffc90001b7a000 0000000000000098 ffff88002d0e7b10
[   68.869056]  ffffffffc042c968 ffffffffad6cdcc0 ffff88002d0e7b10 ffff88002d0e7a78
[   68.869056]  ffffc90001d46afd ffff8800007f96b0 ffffffff00007afd ffffc90001b7a000
[   68.869056] Call Trace:
[   68.869056]  [<ffffffffc042c968>] record_event_consumer.part.2+0x288/0x570 [sysdigcloud_probe]
[   68.869056]  [<ffffffffc042cc73>] record_event_consumer+0x23/0x30 [sysdigcloud_probe]
[   68.869056]  [<ffffffffc042cf3d>] record_event_all_consumers+0x5d/0x90 [sysdigcloud_probe]
[   68.869056]  [<ffffffffc042d00e>] sched_switch_probe+0x3e/0x60 [sysdigcloud_probe]
[   68.869056]  [<ffffffffab54f632>] __schedule+0x4a2/0x9d0
[   68.869056]  [<ffffffffab54fd98>] preempt_schedule_common+0x18/0x30
[   68.869056]  [<ffffffffab54fdcc>] _cond_resched+0x1c/0x30
[   68.869056]  [<ffffffffab551b72>] mutex_lock+0x12/0x30
[   68.869056]  [<ffffffffab2472f2>] kernfs_iop_permission+0x32/0x60
[   68.869056]  [<ffffffffab1dac3b>] __inode_permission+0x6b/0xb0
[   68.869056]  [<ffffffffab1dac98>] inode_permission+0x18/0x50
[   68.869056]  [<ffffffffab1db30b>] link_path_walk+0x26b/0x560
[   68.869056]  [<ffffffffab1daec4>] ? path_init+0x1f4/0x3d0
[   68.869056]  [<ffffffffab1dd349>] path_openat+0xa9/0x14e0
[   68.869056]  [<ffffffffab2c50df>] ? blkcg_print_blkgs+0xbf/0xd0
[   68.869056]  [<ffffffffab1df931>] do_filp_open+0x91/0x100
[   68.869056]  [<ffffffffab0bc921>] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20
[   68.869056]  [<ffffffffab1ed018>] ? __alloc_fd+0xc8/0x180
[   68.869056]  [<ffffffffab1ce65b>] do_sys_open+0x13b/0x230
[   68.869056]  [<ffffffffab10e391>] ? __audit_syscall_entry+0xb1/0x100
[   68.869056]  [<ffffffffab1ce76e>] SyS_open+0x1e/0x20
[   68.869056]  [<ffffffffab554062>] tracesys_phase2+0x84/0x89
[   68.869056] Code: 00 00 48 63 b0 38 04 00 00 45 31 c0 31 c9 31 d2 e8 d4 ef ff ff 85 c0 0f 85 dc 00 00 00 48 8b 43 38 45 31 c0 31 c9 31 d2 48 89 df <48> 8b b0 88 05 00 00 e8 b2 ef ff ff 85 c0 0f 85 ba 00 00 00 48 
[   68.869056] RIP  [<ffffffffc042fb22>] f_sched_switch_e+0x52/0x140 [sysdigcloud_probe]
[   68.869056]  RSP <ffff88002d0e7a20>
[   68.869056] CR2: 0000000000000589
[   68.869056] ---[ end trace 725371bc69642548 ]---
[   68.869056] Kernel panic - not syncing: Fatal exception
[   68.869056] Shutting down cpus with NMI
[   68.869056] Kernel Offset: 0x2a000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[H[J[1;1H[?25l[m[H[J[1;1H[2;27HGNU GRUB  version 2.02~beta2
```

**Comment by gianlucaborello** [comment] 2016-01-22 18:10
Confirmed, we saw it yesterday. We are actively working in determining the root cause of this.

**Comment by gianlucaborello** [comment] 2016-01-23 01:23
This was fixed with https://github.com/draios/sysdig/commit/fdea463fca3f36b14cf3ff8a0fc9a67a229114ef, 4.4 changed the tracepoint API and that caused sysdig to break. A new release including the fix is currently building now.

**Closed by gianlucaborello** 2016-01-23 01:23 UTC
