### ISSUE TITLE
Bug in get_thread_table?

### ISSUE THREAD

**Issue by frioux** [draios/sysdig#429] opened 2015-08-28 04:21 UTC
I'm working on a fairly complex chisel to basically reimplement pstree.  It's not yet complete ([code is here](https://github.com/frioux/sysdig/tree/pstree)) but when it is I'll send a pull request.

Anyway, all that to say I think I've found a bug.  For example, here is a
snippet of the output from pstree:

```
├─docker─┬─my_init───runsvdir─┬─runsv
│        │                    ├─runsv─┬─sudo───multilog
│        │                    │       └─sudo───runsvdir─┬─runsv─┬─monit───{monit}
```

Here is the version I've implemented:

```
├─docker─┬─my_init───runsvdir─┬─runsv
│        │                    ├─runsv───cron
│        │                    ├─runsv───tail
│        │                    ├─runsv───syslog-ng
│        │                    └─runsv─┬─sudo───multilog
│        │                            └─sudo───runsvdir─┬─runsv─┬─monit
│        │                                              │       ├─multilog
│        │                                              │       └─{monit}
```

Note the parts with the braces in the the screenshot.  The braces mean it's a thread.  Basically all threads in sysdig have the wrong parent.  I would expect their parent to be the process they are in, so the monit thread is running inside of the monit process.  I can confirm this by looking in the proc filesystem.  But with sysdig the ptid is set to the processes parent.

Am I misunderstanding something?

**Comment by ldegio** [comment] 2015-08-28 05:04
Can you share a small capture that shows the problem?

**Comment by frioux** [comment] 2015-08-29 01:12
Yeah how should I share it?  It seems like a trace of a single event on my system is a full 1m, presumably due to enumeration of various stuff from /proc and /etc.

**Comment by frioux** [comment] 2015-09-02 06:03
Trying to see if just attaching to a response will work

On Thu, Aug 27, 2015 at 10:04:16PM -0700, Loris Degioanni wrote:
> Can you share a small capture that shows the problem?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/draios/sysdig/issues/429#issuecomment-135636725

-- 
fREW Schmidt
https://blog.afoolishmanifesto.com

**Comment by luca3m** [comment] 2015-09-02 08:09
Can you upload it to dropbox or even a free hosting solution like [transfer.sh](https://transfer.sh)?

**Comment by frioux** [comment] 2015-09-02 16:21
Ok, I sent a trace directly to the two of you, as I am nervous about sharing a systemwide trace with the world.  Note that you can easily see the issue by tracing your own system with either Firefox or Chrome running, as they both have lots of threads and the threads have the wrong parents.

**Comment by ldegio** [comment] 2015-09-04 18:01
Thanks for the file.

Looks like the cause is: sysdig extracts parent information of a thread from the PPid entry in /proc/<pid>/task/<tid>/status. Turns out that the PPid value for a thread does *not* contain the id of its creator, but is instead the pid of the *creator of the main process*. As a consequence, we don't have a way to report the information you need.

What I assume pstree does, and what I suggest you to do, is checking if an entry in the thread table is not a main thread, and in that case use pid instead of ppid.

I'm going to assume this is satisfactory and close the issue. Feel free to reopen if it's not.

**Closed by ldegio** 2015-09-04 18:01 UTC

**Comment by frioux** [comment] 2015-09-04 18:06
Thanks, I appreciate the help and will reopen this if that doesn't work for some reason.
